name: Build Clash Config

on:
  schedule:
    - cron: "0 3 * * *"   # هر روز 03:00 UTC (06:30 ایران تقریبی)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run converter
        run: python convert.py

      - name: Commit result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config.yaml
          git commit -m "Auto update config"
          git push
